HUSINSA-master/HUSINSA/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    path('', redirection, name='redirect'),
]

HUSINSA-master/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name = "account"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("signup/", signup,name = "signup"),
    path("user/detail/", userDetail,name = "userDetail"),
    path("user/image/update", userImageUpdate,name = "image_update"),

]

HUSINSA-master/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("HUSINSA.urls")),
    path("account/",include("account.urls")),
    path("item/",include("item.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HUSINSA-master/item/urls.py
from django.urls import path
from .views import *

app_name = "item"

urlpatterns = [
    path('clothe/list/<str:category>', clothe_list, name='clothe_list'),
    path('clothe/<int:id>/', clothe_detail, name='clothe_detail'),
    path('clothe/like/', clothe_like, name='clothe_like'),
    path('cart/list/', cart_list, name='cart_list'),
    path('cart/create/', cart_create, name='cart_create'),
    path('order/list/', order_list, name='order_list'),
    path('order/create/', order_create, name='order_create'),
    path('order/all/', order_all, name='order_all'),
]

HUSINSA-master/HUSINSA/models.py
from django.db import models

# Create your models here.

HUSINSA-master/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to = "user",default = "default.png")
    likes = models.ManyToManyField("item.Clothe")

HUSINSA-master/item/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length = 100)

    def __str__(self):
        return self.name

class Clothe(models.Model):
    name = models.CharField(max_length = 100,null= False)
    brand = models.CharField(max_length = 100,null= False)
    price = models.IntegerField(null = False)
    image = models.ImageField(upload_to = "product")
    category = models.ForeignKey(Category,on_delete = models.CASCADE)

class Cart(models.Model):
    user = models.ForeignKey("account.user",on_delete=models.CASCADE)
    clothe = models.ForeignKey(Clothe,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)
    ordered = models.BooleanField(default = False)

HUSINSA-master/HUSINSA/views.py
from django.shortcuts import redirect

def redirection(request):
    return redirect("item:clothe_list","all")

HUSINSA-master/account/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from .models import User

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if User.objects.filter(username = request.POST.get("username")).exists():
            return render(request,"signup.html",{"message":"이미 존재하는 회원입니다."})
        else:
            user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password'],
                first_name=request.POST['name'][0],
                last_name=request.POST['name'][1:],
            )
            auth.login(request, user)
            return redirect('item:clothe_list','all')

    else:
        return render(request, 'account/signup.html')

def userDetail(request):
    return render(request,"account/mypage.html")

def userImageUpdate(request):
    request.user.image = request.FILES.get("image")
    request.user.save()
    return redirect('account:userDetail')

HUSINSA-master/item/views.py
from django.shortcuts import render, redirect
from .models import Clothe, Cart,Category
import json
from django.http import JsonResponse

def clothe_list(request,category):
    if category == "all":
        context = {
            "clothe_list" : Clothe.objects.all()
        }
    else:
        category = Category.objects.get(name = category)
        context = {
            "clothe_list" : Clothe.objects.filter(category=category)
        }

    return render(request,"item/index.html",context)

def clothe_detail(request,id):
    context = {
        "clothe" : Clothe.objects.get(id= id)
    }

    return render(request,"item/itemDetail.html",context)

def clothe_like(request):
    if request.method == "POST":
        data = json.loads(request.body)
        clothe = Clothe.objects.get(id = data['id'])
        request.user.likes.add(clothe)

        return JsonResponse({},status = 200)
    else:
        context = {
            "clothe_list" : request.user.likes.all()
        }

        return render(request,"item/myLike.html",context)

def cart_list(request):
    context = {
        "cart_list" : Cart.objects.filter(user = request.user,ordered = False).order_by("-created_at")
    }
    return render(request,"item/cart.html",context)

def cart_create(request):
    data = json.loads(request.body)
    cart = Cart.objects.create(
        user = request.user,
        clothe = Clothe.objects.get(id = data['id']),
    )
    return JsonResponse({},status = 200)

def order_list(request):
    context = {
        "order_list" : Cart.objects.filter(user = request.user,ordered = True).order_by("-created_at")
    }
    print(context)

    return render(request,"item/buyComplete.html",context)

def order_create(request):
    data = json.loads(request.body)
    cart = Cart.objects.create(
        user = request.user,
        clothe = Clothe.objects.get(id = data['id']),
        ordered = True
    )
    return JsonResponse({},status = 200)

def order_all(request):
    carts = Cart.objects.filter(user = request.user, ordered = False)
    for cart in carts:
        cart.ordered=True
        cart.save()
    return redirect("item:clothe_list","all")

HUSINSA-master/templates/item/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block static %}
    {% endblock %}
</head>
<body>
    <div class="main_wrap">
        <div class="main_nav">
            <img src="{% static 'img/blackLogo.jpeg' %}"  onclick="location.href='{% url 'main:redirect' %}'"/>
        </div>
        <div class="main_member">
            {% if user.is_authenticated %}
                <button type="button" onclick="location.href='{% url 'account:logout' %}'">로그아웃</button>
                <div>
                    <p onclick="location.href='{% url 'account:userDetail' %}'">마이페이지</p>
                    <p id="likePage" onclick="location.href='{% url 'item:clothe_like' %}'">좋아요</p>
                    <p onclick="location.href='{% url 'item:cart_list' %}'">장바구니</p>

                </div>
            {% else %}
                <button type="button" onclick="location.href='{% url 'account:login' %}'">로그인</button>
                <div>
                    <p id="promotion">지금 회원가입 하시고 후신사를 즐겨보세용</p>
                </div>
            {% endif %}

        </div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

HUSINSA-master/templates/item/buyComplete.html
{% extends 'item/base.html' %}
{% load static %}

{% block static %}
  <title>좋아요 목록</title>
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
  <h3 class="like_item_title">🅾️ 구매 목록  🅾️</h3>
  <div class="like_box_wrap">
    {% for order in order_list %}
      <div class="item_box">
        <img src="{{order.clothe.image.url}}"/>
        <div>
          <p id="item_brand">{{oreder.clothe.brand}}</p>
          <p id="item_name">{{order.clothe.name}}</p>
          <p id="item_price">{{order.clothe.price}}원</p>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

HUSINSA-master/templates/item/cart.html
{% extends 'item/base.html' %}
{% load static %}

{% block static %}
  <title>좋아요 목록</title>
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
  <div class="cart_title_wrap">
    <h3 class="like_item_title">🛒 장바구니  🛒</h3>
    <button type="button" id="buyBt" onclick = "location.href = '{% url 'item:order_all' %}'">BUY</button>
  </div>
  <div class="like_box_wrap">
    {% for cart in cart_list %}
      <div class="item_box">
        <img src="{{cart.clothe.image.url}}"/>
        <div>
          <p id="item_brand">{{cart.clothe.brand}}</p>
          <p id="item_name">{{cart.clothe.name}}</p>
          <p id="item_price">{{cart.clothe.price}}원</p>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}
</div>
</div>
</body>
</html>

HUSINSA-master/templates/item/index.html
{% extends 'item/base.html' %}
{% load static %}

{% block static %}
    <title>후신사</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
{% endblock %}

{% block content %}

        <div class="category_item_wrap">
            <div class="category_wrap">
                <h3>카테고리</h3>
                <p onclick="location.href = '{% url 'item:clothe_list' 'all' %}'">전체</p>
                <p onclick="location.href = '{% url 'item:clothe_list' 'shirts' %}'">상의</p>
                <p onclick="location.href = '{% url 'item:clothe_list' 'pants' %}'">하의</p>
                <p onclick="location.href = '{% url 'item:clothe_list' 'shoes' %}';">신발</p>
            </div>

            <div class="item_wrap">
                {% for clothe in clothe_list %}
                    <div class = "item_box" onclick="location.href = '{% url 'item:clothe_detail' clothe.id %}'">
                        <img src = "{{clothe.image.url}}">
                        <div>
                            <p id = "item_brand">{{clothe.brand}}</p>
                            <p id = "item_brand">{{clothe.name}}</p>
                            <p id = "item_price">{{clothe.price}}원</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

{% endblock %}

HUSINSA-master/templates/item/itemDetail.html
{% extends 'item/base.html' %}
{% load static %}

{% block static %}
    <title>상품 조회</title>
    <link rel="stylesheet" href="{% static 'css/itemDetail.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="{% static 'js/itemDetail.js' %}"></script>
{% endblock %}

{% block content %}
        <div class="itemDetail_wrap">
            <h3>상품 조회</h3>
            <div>
                <img id="itemImg" src = "{{clothe.image.url}}"/>
                <div class="item_box">
                    <div class="item_info">
                        <div class="product_info">
                            <h3>Product Info</h3>
                            <p>제품정보</p>
                        </div>
                        <div class="brand_name">
                            <p>브랜드</p>
                            <p id="brandName">{{clothe.brand}}</p>
                        </div>
                        <div class="item_name">
                            <p>이름</p>
                            <p id="itemName">{{clothe.name}}</p>
                        </div>
                    </div>
                    <div id="division"></div>
                    <div>
                        <div class="item_price">
                            <h3>Price Info</h3>
                            <p>가격정보</p>
                        </div>
                        <div class="sale_price">
                            <p>판매가</p>
                            <p id="salePrice">{{clothe.price}}원</p>
                        </div>
                    </div>
                    <div class="sale_bt">
                        <button type="button" class="saleBt" onclick="buyItem({{clothe.id}});">바로구매</button>
                        <div>
                            <div class="heart_icon_wrap" onclick="likeItem({{ clothe.id }});">
                                <img src="{% static 'img/heart.png' %}" id="heartImage{{ clothe.id }}">
                            </div>
                            <div class="cart_icon_wrap" onclick="pushCart({{clothe.id}});">
                                <img src="{% static 'img/cart.png' %}"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

HUSINSA-master/templates/item/myLike.html
{% extends 'item/base.html' %}
{% load static %}

{% block static %}
    <title>좋아요 목록</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
    <h3 class="like_item_title">♥️ 좋아요 누른 상품  ♥️</h3>
    <div class="like_box_wrap">
      {% for clothe in clothe_list %}
        <div class="item_box">
          <img src="{{clothe.image.url}}"/>
          <div>
            <p id="item_brand">{{clothe.brand}}</p>
            <p id="item_name">{{clothe.name}}</p>
            <p id="item_price">{{clothe.price}}원</p>
          </div>
        </div>
      {% endfor %}
    </div>
{% endblock %}